---
kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: test
  pull: always
  image: quay.io/coreos/jsonnet-ci:latest
  commands:
  # This step requires >=go1.12 and promtool
  - make test

- name: lint
  pull: always
  image: quay.io/coreos/jsonnet-ci:latest
  commands:
  # This step requires golancilint, promtool and jsonnetfmt
  - make lint

- name: build
  pull: always
  image: golang:1.13
  commands:
  - make observatorium

- name: tags
  image: golang:1.13
  commands:
  - echo -n "$(git rev-parse --abbrev-ref HEAD | tr / -)-$(date +%Y-%m-%d)-$(git rev-parse --short HEAD),latest" > .tags
  when:
    branch:
    - master
    event:
    - push

- name: docker-test
  image: plugins/docker
  settings:
    dry_run: true
    repo: quay.io/observatorium/observatorium
  when:
    branch:
    event:
    - pull-request
