version: 2
jobs:
  build:
    docker:
      - image: golang:1.13
    steps:
      - checkout
      - run: |
          make observatorium
          git diff --exit-code

  lint:
    docker:
      - image: golang:1.13
    steps:
      - checkout
      - run: |
          apt-get update && apt-get install xz-utils
          make lint --always-make

  test:
    docker:
      - image: golang:1.13
    steps:
      - checkout
      - run: |
          apt-get update && apt-get install xz-utils
          make test --always-make

  generate:
    docker:
      - image: golang:1.13
    steps:
      - checkout
      - run: |
          make README.md
          make generate --always-make
          git diff --exit-code

  container-push:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: |
          echo "$DOCKER_PASS" | docker login quay.io --username $DOCKER_USER --password-stdin
          make container-push

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - lint
      - test
      - generate
  tagged-master:
    jobs:
      - container-push:
          filters:
            tags:
              only: /^v.*/
            branches:
              only:
                - master
  commit-master:
    jobs:
      - build
      - lint
      - test
      - generate
      - container-push:
          requires:
            - build
          filters:
            branches:
              only:
                - master
