apiVersion: v1
data:
  rbac.yaml: |-
    "roleBindings":
    - "name": "telemeter"
      "roles":
      - "read-write"
      "subjects":
      - "admin@example.com"
    "roles":
    - "name": "read-write"
      "permissions":
      - "read"
      - "write"
      "resources":
      - "metrics"
      "tenants":
      - "telemeter"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: observatorium-api
    app.kubernetes.io/name: observatorium-api
    app.kubernetes.io/version: master-2020-06-22-v0.1.1-100-g571ce24
  name: observatorium-api
  namespace: observatorium
