apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: observatorium-api
    app.kubernetes.io/name: observatorium-api
    app.kubernetes.io/version: master-2020-05-04-v0.1.1-21-gabb9864
  name: observatorium-api
  namespace: observatorium
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/component: api
      app.kubernetes.io/instance: observatorium-api
      app.kubernetes.io/name: observatorium-api
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: api
        app.kubernetes.io/instance: observatorium-api
        app.kubernetes.io/name: observatorium-api
        app.kubernetes.io/version: master-2020-05-04-v0.1.1-21-gabb9864
    spec:
      containers:
      - args:
        - --web.listen=0.0.0.0:8080
        - --web.internal.listen=0.0.0.0:8081
        - --metrics.read.endpoint=http://127.0.0.1:9091
        - --metrics.write.endpoint=http://127.0.0.1:19291
        - --log.level=warn
        image: quay.io/observatorium/observatorium:master-2020-05-04-v0.1.1-21-gabb9864
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /live
            port: 8081
            scheme: HTTP
          periodSeconds: 30
        name: observatorium-api
        ports:
        - containerPort: 8081
          name: internal
        - containerPort: 8080
          name: public
        readinessProbe:
          failureThreshold: 12
          httpGet:
            path: /ready
            port: 8081
            scheme: HTTP
          periodSeconds: 5
