apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: observatorium-api
    app.kubernetes.io/name: observatorium-api
    app.kubernetes.io/version: master-2020-06-16-v0.1.1-86-g25a3e86
  name: observatorium-api
  namespace: observatorium
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/component: api
      app.kubernetes.io/instance: observatorium-api
      app.kubernetes.io/name: observatorium-api
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: api
        app.kubernetes.io/instance: observatorium-api
        app.kubernetes.io/name: observatorium-api
        app.kubernetes.io/version: master-2020-06-16-v0.1.1-86-g25a3e86
    spec:
      containers:
      - args:
        - --web.listen=0.0.0.0:8080
        - --web.internal.listen=0.0.0.0:8081
        - --logs.read.endpoint=http://127.0.0.1:3100
        - --logs.tail.endpoint=http://127.0.0.1:3100
        - --logs.write.endpoint=http://127.0.0.1:3100
        - --metrics.read.endpoint=http://127.0.0.1:9091
        - --metrics.write.endpoint=http://127.0.0.1:19291
        - --log.level=warn
        - --rbac.config=/etc/observatorium/rbac.yaml
        - --tenants.config=/etc/observatorium/tenants.yaml
        - --web.healthchecks.url=https://127.0.0.1:8080
        - --tls.server.cert-file=/mnt/certs/server.pem
        - --tls.server.key-file=/mnt/certs/server.key
        - --tls.healthchecks.cert-file=/mnt/certs/client.pem
        - --tls.healthchecks.key-file=/mnt/certs/client.key
        - --tls.healthchecks.server-ca-file=/mnt/certs/ca.pem
        - --tls.reload-interval=1m
        image: quay.io/observatorium/observatorium:master-2020-06-16-v0.1.1-86-g25a3e86
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /live
            port: 8081
            scheme: HTTP
          periodSeconds: 30
        name: observatorium-api
        ports:
        - containerPort: 8081
          name: internal
        - containerPort: 8080
          name: public
        readinessProbe:
          failureThreshold: 12
          httpGet:
            path: /ready
            port: 8081
            scheme: HTTP
          periodSeconds: 5
        volumeMounts:
        - mountPath: /etc/observatorium/rbac.yaml
          name: rbac
          readOnly: true
          subPath: rbac.yaml
        - mountPath: /etc/observatorium/tenants.yaml
          name: tenants
          readOnly: true
          subPath: tenants.yaml
        - mountPath: /mnt/certs
          name: certs
          readOnly: true
      volumes:
      - configMap:
          name: observatorium-api
        name: rbac
      - name: tenants
        secret:
          secretName: observatorium-api
      - name: certs
        secret:
          secretName: observatorium-api-tls-certs
