apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: observatorium-api
    app.kubernetes.io/name: observatorium-api
    app.kubernetes.io/version: master-2020-05-04-v0.1.1-21-gabb9864
  name: observatorium-api
  namespace: observatorium
spec:
  ports:
  - name: internal
    port: 8081
    targetPort: 8081
  - name: public
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: observatorium-api
    app.kubernetes.io/name: observatorium-api
